runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /fonts/.*
    static_dir: fonts

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto